doorsWeb/doorsWeb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doorsWeb/website/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',homePage,name="home"),
    path('fenster',fenster,name="fenster"),
    path('kunalufenster',kunAluFenster,name="kunalufenster"),
    path('holzalufenster',holzAluFenster,name="holzalufenster"),
    path('holzfenster',holzfenster,name="holzfenster"),
    path('turen',turen,name="turen"),
    path('toranlagen',toranlagen,name="toranlagen"),
    path('sonnen',sonnen,name="sonnen"),
    path('kontakt',kontakt,name="kontakt"),
    path('datenschutzerklärung',Datenschutzerklärung,name="datenschutzerklärung"),
    path('impressum',impressum,name="impressum"),
]

doorsWeb/website/models.py
from django.db import models

# Create your models here.

class PhoneNumber(models.Model):
    number = models.CharField(max_length=200)
    def __str__(self):
        return self.number
    

class Email(models.Model):
    email = models.CharField(max_length=200)
    def __str__(self):
        return self.email
    
class Location(models.Model):
    location=models.TextField(blank=True,null=True)

class Map(models.Model):
    map_link=models.TextField(blank=True,null=True)
    

class OpeningHours(models.Model):
    Days = models.CharField(max_length=200)
    def __str__(self):
        return self.Days
    
class Hours(models.Model):
    days=models.ForeignKey(OpeningHours,on_delete=models.CASCADE)
    Hours = models.CharField(max_length=200)




class HomePage(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)

class PTagHome(models.Model):
    home=models.ForeignKey(HomePage,on_delete=models.CASCADE)
    parag=models.TextField(blank=True,null=True)




class FensterPage(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)

class Fenster(models.Model):
    fensterpage=models.ForeignKey(FensterPage,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)
    innerTitle=models.CharField(max_length=250,blank=True,null=True)
    text=models.TextField(blank=True,null=True)
    bottom=models.CharField(max_length=250,blank=True,null=True)

class FensterPoints(models.Model):
    fenster=models.ForeignKey(Fenster,on_delete=models.CASCADE)
    point=models.CharField(max_length=250,blank=True,null=True)



class KunAluFensterPage(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)

class AluFenster(models.Model):
    fensterpage=models.ForeignKey(KunAluFensterPage,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)
    innerTitle=models.CharField(max_length=250,blank=True,null=True)
    text=models.TextField(blank=True,null=True)
    bottom=models.CharField(max_length=250,blank=True,null=True)



class HolzAluFensterPage(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)

    def __str__(self):
        return self.title

class HolzAluFenster(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)
    #innerTitle=models.CharField(max_length=250,blank=True,null=True)
    #text=models.TextField(blank=True,null=True)
    #bottom=models.CharField(max_length=250,blank=True,null=True)
    def __str__(self):
        return self.title

class HolzAluImages(models.Model):
    holzalufenster=models.ForeignKey(HolzAluFenster,on_delete=models.CASCADE)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Carousel Image'

class HolzAluSidePoints(models.Model):
    holzalufenster=models.ForeignKey(HolzAluFenster,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    description=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Side Point'


class HolzAluBottomImage(models.Model):
    holzalufenster=models.ForeignKey(HolzAluFenster,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    description=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Bottom Image'





class HolzFenster(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)
    #innerTitle=models.CharField(max_length=250,blank=True,null=True)
    #text=models.TextField(blank=True,null=True)
    #bottom=models.CharField(max_length=250,blank=True,null=True)
    def __str__(self):
        return self.title

class HolzImages(models.Model):
    holzfenster=models.ForeignKey(HolzFenster,on_delete=models.CASCADE)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Carousel Image'

class HolzSidePoints(models.Model):
    holzfenster=models.ForeignKey(HolzFenster,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    description=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Side Point'


class HolzBottomImage(models.Model):
    holzfenster=models.ForeignKey(HolzFenster,on_delete=models.CASCADE)
    title=models.CharField(max_length=250,blank=True,null=True)
    description=models.CharField(max_length=250,blank=True,null=True)
    image=models.ImageField(blank=True,null=True)

    class Meta:
        verbose_name='Bottom Image'






class TurenPage(models.Model):
    text=models.TextField(blank=True,null=True)
    button_text=models.CharField(max_length=250,blank=True,null=True)
    button_link=models.CharField(max_length=250,blank=True,null=True)





class ToranLagenPage(models.Model):
    title=models.CharField(max_length=250,blank=True,null=True)
    subtitle=models.CharField(max_length=250,blank=True,null=True)
    inner_title=models.CharField(max_length=250,blank=True,null=True)

class ToranLangenImage(models.Model):
    toranpage=models.ForeignKey(ToranLagenPage,on_delete=models.CASCADE)
    image=models.ImageField(blank=True,null=True)

doorsWeb/website/views.py
from django.shortcuts import render
from .models import *

# Create your views here.


def homePage(request):
    context=contextReturn()
    home=HomePage.objects.all().first()
    context_2={
        'home':home
    }
    context.update(context_2)
    return render(request,"website/home.html",context=context)

def fenster(request):
    context=contextReturn()
    fenster=FensterPage.objects.all().first()
    context_2={
        'fenster':fenster
    }
    context.update(context_2)
    return render(request,"website/fenster.html",context=context)

def kunAluFenster(request):
    context=contextReturn()
    alufenster=KunAluFensterPage.objects.all().first()
    context_2={
        'alufenster':alufenster
    }
    context.update(context_2)
    return render(request,"website/kunAluFenster.html",context=context)

def holzAluFenster(request):
    context=contextReturn()
    holzalufenster=HolzAluFenster.objects.all()
    context_2={
        'holzalufenster':holzalufenster
    }
    context.update(context_2)
    return render(request,"website/holzAluFenster.html",context=context)

def holzfenster(request):
    context=contextReturn()
    holzfenster=HolzFenster.objects.all()
    context_2={
        'holzfenster':holzfenster
    }
    context.update(context_2)
    return render(request,"website/holzfenster.html",context=context)

def turen(request):
    context=contextReturn()
    turen=TurenPage.objects.all().first()
    context_2={
        'turen':turen
    }
    context.update(context_2)
    return render(request,"website/tueren.html",context=context)

def sonnen(request):
    context=contextReturn()
    return render(request,"website/sonnen-und-insektenschutz.html",context=context)

def toranlagen(request):
    context=contextReturn()
    langen=ToranLagenPage.objects.all().first()
    context_2={
        'langen':langen
    }
    context.update(context_2)
    return render(request,"website/toranlagen.html",context=context)

def kontakt(request):
    context=contextReturn()
    return render(request,"website/kontakt.html",context=context)

def Datenschutzerklärung(request):
    context=contextReturn()
    return render(request,"website/Datenschutzerklärung.html",context=context)

def impressum(request):
    context=contextReturn()
    return render(request,"website/impressum.html",context=context)








def contextReturn():
    number=PhoneNumber.objects.all().first()
    openingHours=OpeningHours.objects.all()
    location=Location.objects.all().first()
    email=Email.objects.all().first()
    map_link=Map.objects.all().first()
    context={
        'number':number,
        'openingHours':openingHours,
        'location':location,
        'email':email,
        'map_link':map_link
    }
    return context

doorsWeb/website/templates/website/holzAluFenster.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOLZ ALU FENSTER - Fenster Pro Ramani Afrim</title>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="/static/css/main.css">
    <link href="https://css.gg/css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="overlay" id="hide-overlay"></div>
    <header >
        <div class="mainHeader">
            <!-- sticky contact -->
            <div class="mainHeader-Top">
                <div class="container mainHeade-minHeight">
                    <div class="mainHeader-Top-Text">
                        Haben Sie Fragen? Rufen Sie uns an: <span style="color: orange;">+43 {{number.number}}</span>
                    </div>
                </div>
            </div>
            

            <!-- sticky navbar -->
            <div style="background-color: rgba(255, 255, 255, 1);">
                <div class="container">
                    <div style="display: flex;">
                        <!-- logo -->
                        <a href="{% url 'home' %}"><img src="/static/images/logo.jpg" alt="" style="width: 150px; min-width: 150px; max-inline-size: 150%; margin-right: 10px;"></a>
                        
        
                        <nav style="margin: 30px;"  id="mainMenu">
                            <ul class="menu">
                                <li class="nav-link">
                                    <a href="#">FENSTER
                                        <ul class="subMenu">
                                            <li><a href="{% url 'fenster' %}">FENSTER</a></li>
                                            <li><a href="{% url 'kunalufenster' %}">KUNSTSTOFF ALU FENSTER</a></li>
                                            <li><a href="{% url 'holzalufenster' %}">HOLZ ALU FENSTER</a></li>
                                            <li><a href="{% url 'holzfenster' %}">HOLZFENSTER</a></li>
                                        </ul>
                                    </a>
                                </li>

                                <li class="nav-link"><a href="{% url 'turen' %}">TÜREN</a></li>

                                <li class="nav-link"><a href="{% url 'toranlagen' %}">TORANLAGEN</a></li>

                                <li class="nav-link"><a href="{% url 'sonnen' %}">SONNEN-UND INSEKTENSCHUTZ</a></li>
                                
                                <li class="nav-link"><a href="{% url 'kontakt' %}">KONTAKT</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <label class="hamburger-menu" >
                <input type="checkbox" id="hamMenu" />
            </label>
            <aside class="sidebar">
            <nav class="hamburger-links">
                <ul class="">
                    <li class="nav-link">
                        <a href="#">FENSTER
                            <ul class="subMenu">
                                <li><a href="{% url 'fenster' %}">FENSTER</a></li>
                                <li><a href="{% url 'kunalufenster' %}">KUNSTSTOFF ALU FENSTER</a></li>
                                <li><a href="{% url 'holzalufenster' %}">HOLZ ALU FENSTER</a></li>
                                <li><a href="{% url 'holzfenster' %}">HOLZFENSTER</a></li>
                            </ul>
                        </a>
                    </li>

                    <li class="nav-link"><a href="{% url 'turen' %}">TÜREN</a></li>

                    <li class="nav-link"><a href="{% url 'toranlagen' %}">TORANLAGEN</a></li>
                    
                    <li class="nav-link"><a href="{% url 'sonnen' %}">SONNEN-UND INSEKTENSCHUTZ</a></li>
                    
                    <li class="nav-link"><a href="{% url 'kontakt' %}">KONTAKT</a></li>
                </ul>
            </nav>
            </aside>
            
        </div>
    </header>

    <main>
        <!-- main section -->
        <div class="main-sec1-1">
            <div class="main-sec1-2" style="height: 1000px;">
                <div class="main-sec1-3">
                    <div class="main-sec1-4">
                        
                    </div>
                </div>
            </div>
        </div>

        <!-- 1 -->
        <div>
            <div class="container">
                {% for fen in holzalufenster %}
                <h3 style="margin-top: 50px;">{{fen.title}}</h3>
                <div class="icon-list">

                    <div class="col-md-6 col-xs-12 print-6">
                        <div class="main-carousel"
                            data-flickity='{"autoPlay": 3000,"pageDots": true,"wrapAround":true}'>
                            {% for carimage in fen.holzaluimages_set.all %}
                            <div class="carousel-cell">
                                <img src="{{carimage.image.url}}" alt="">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 print-6">
                        <table class="tabulka_ikony" border="0">
                            <tbody>
                                {% for icon in fen.holzalusidepoints_set.all %}
                                <tr>
                                    <td><img title="{{icon.title}}" src="{{icon.image.url}}" alt="{{icon.title}}" width="50"
                                            height="50"></td>
                                    <td>
                                        <h3>{{icon.title}}</h3>
                                        <p>{{icon.description}}</p>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row" style="text-align: center;"><!-- sekcion 01 -->
                    {% for bottom in fen.holzalubottomimage_set.all %}
                    <div class="col-xs-8 col-xs-offset-2 col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-0"><img
                            style="border: 1px solid #d5d5d5;" title="Niedrige Komfort-Schwelle" src="{{bottom.image.url}}"
                            alt="Niedrige Komfort-Schwelle" width="708" height="320">
                        <div style="text-align: center;">
                            <h3  style="text-align: center;">{{bottom.title}}</h3>
                            <p>{{bottom.description}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <hr>
                {% endfor %}
            </div>




            <!-- 5 -->
            <div
                style="background-image: url('/static/images/endPic.jpg'); background-repeat: no-repeat; background-position: 0% 0%; background-attachment: fixed; background-size:cover;">
                <div
                    style="height: 459px; padding-top: 88px; padding: 88px 50px 0px 50px; margin: 0px auto; max-width: 1310px; text-align: center;">
                    <h1 class="conth1">BERATUNGSTERMIN VEREINBAREN
                    </h1>
                    <div class="main-sec1-button1">
                        <a href="tel:+43{{number.number}}" class="main-sec1-button2">
                            <span style="text-wrap: nowrap;">
                                +43 {{number.number}}
                            </span>
                        </a>
                    </div>
                </div>
            </div>
    </main>


    <!-- Footer -->
    <footer class="kilimanjaro_area">
        <!-- Top Footer Area Start -->
        <div class="foo_top_header_one section_padding_100_70">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="kilimanjaro_part">
                            <img src="/static/images/logo.jpg" style="max-width: 200px;" alt="">
                        </div>
                    </div>
                    
                    <div class="col-12  col-lg-3 kili-flex">
                        <div class="kilimanjaro_part">
                            <h5>KONTAKT</h5>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Telefon:</h5>
                                <p>+43 {{number.number}}</p>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Email:</h5>
                                <p style="font-size: 1rem;">office@fensterpro.at</p>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Whatsapp:</h5>
                                <a aria-label="Chat on WhatsApp" href="https://wa.me/43{{number.number}}"> <img alt="Chat on WhatsApp" src="/static/images/WhatsAppButtonWhiteSmall.svg" />
                                </a>
                            </div>
                        </div>

                        <div class="kilimanjaro_part">
                            <h5>ÖFFNUNGSZEITEN</h5>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Montag – Donnerstag</h5>
                                <p>8:00 – 12:00 Uhr</p>
                                <p>13:00 – 16:00 Uhr</p>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Freitag</h5>
                                <p>8:00 – 12:00 Uhr</p>
                            </div>
                        </div>

                        <div class="kilimanjaro_part">
                            <h5>WICHTIGE LINKS</h5>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>
                                    <a href="{% url 'datenschutzerklärung' %}">Datenschutzerklärung</a>
                                </h5>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>
                                    <a href="{% url 'impressum' %}">Impressum</a>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>



    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script src="/static/js/scripts.js"></script>
</body>

</html>

doorsWeb/website/templates/website/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fenster Pro Ramani Afrim</title>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script defer src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script defer src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="overlay" id="hide-overlay"></div>
    <header >
        <div class="mainHeader">
            <!-- sticky contact -->
            <div class="mainHeader-Top">
                <div class="container mainHeade-minHeight">
                    <div class="mainHeader-Top-Text">
                        Haben Sie Fragen? Rufen Sie uns an: <span style="color: orange;">+43 {{number.number}}</span>
                    </div>
                </div>
            </div>
            

            <!-- sticky navbar -->
            <div style="background-color: rgba(255, 255, 255, 1);">
                <div class="container">
                    <div style="display: flex;">
                        <!-- logo -->
                        <a href="{% url 'home' %}"><img src="/static/images/logo.jpg" alt="" style="width: 150px; min-width: 150px; max-inline-size: 150%; margin-right: 10px;"></a>
                        
        
                        <nav style="margin: 30px;"  id="mainMenu">
                            <ul class="menu">
                                <li class="nav-link">
                                    <a href="#">FENSTER
                                        <ul class="subMenu">
                                            <li><a href="{% url 'fenster' %}">FENSTER</a></li>
                                            <li><a href="{% url 'kunalufenster' %}">KUNSTSTOFF ALU FENSTER</a></li>
                                            <li><a href="{% url 'holzalufenster' %}">HOLZ ALU FENSTER</a></li>
                                            <li><a href="{% url 'holzfenster' %}">HOLZFENSTER</a></li>
                                        </ul>
                                    </a>
                                </li>

                                <li class="nav-link"><a href="{% url 'turen' %}">TÜREN</a></li>

                                <li class="nav-link"><a href="{% url 'toranlagen' %}">TORANLAGEN</a></li>

                                <li class="nav-link"><a href="{% url 'sonnen' %}">SONNEN-UND INSEKTENSCHUTZ</a></li>
                                
                                <li class="nav-link"><a href="{% url 'kontakt' %}">KONTAKT</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <label class="hamburger-menu" >
                <input type="checkbox" id="hamMenu" />
            </label>
            <aside class="sidebar">
            <nav class="hamburger-links">
                <ul class="">
                    <li class="nav-link">
                        <a href="#">FENSTER
                            <ul class="subMenu">
                                <li><a href="{% url 'fenster' %}">FENSTER</a></li>
                                <li><a href="{% url 'kunalufenster' %}">KUNSTSTOFF ALU FENSTER</a></li>
                                <li><a href="{% url 'holzalufenster' %}">HOLZ ALU FENSTER</a></li>
                                <li><a href="{% url 'holzfenster' %}">HOLZFENSTER</a></li>
                            </ul>
                        </a>
                    </li>

                    <li class="nav-link"><a href="{% url 'turen' %}">TÜREN</a></li>

                    <li class="nav-link"><a href="{% url 'toranlagen' %}">TORANLAGEN</a></li>
                    
                    <li class="nav-link"><a href="{% url 'sonnen' %}">SONNEN-UND INSEKTENSCHUTZ</a></li>
                    
                    <li class="nav-link"><a href="{% url 'kontakt' %}">KONTAKT</a></li>
                </ul>
            </nav>
            </aside>
            
        </div>
    </header>
    
    <main>
        <!-- main section -->
        <div class="main-sec1-1">
            <div class="main-sec1-2">
                <div class="main-sec1-3">
                    <div class="main-sec1-4">
                        <!-- <h1>
                            SOMMER SONNE
                            <br>
                            SONNENSEHEN
                        </h1> -->
    
                    </div>
                </div>
            </div>
        </div>

        <!-- 1 -->
        <div class="sec1-1">
            <div class="container">
                <div class="sec1-2">
                    <div class="twothirds">
                        <h2>{{home.title}}</h2>
                        {% for par in home.ptaghome_set.all%}
                            <p>{{par.parag}}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <!-- 5 -->
        <div style="background-image: url('/static/images/endPic.jpg'); background-repeat: no-repeat; background-position: 0% 0%; background-attachment: fixed; background-size:cover;">
            <div style="height: 459px; padding-top: 88px; padding: 88px 50px 0px 50px; margin: 0px auto; max-width: 1310px; text-align: center;">
                <h1 class="conth1">BERATUNGSTERMIN VEREINBAREN
                </h1>
                <div class="main-sec1-button1">
                    <a href="tel:+43{{number.number}}" class="main-sec1-button2">
                        <span style="text-wrap: nowrap;">
                            +43 {{number.number}}
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </main>

    
    <!-- Footer -->
    <footer class="kilimanjaro_area">
        <!-- Top Footer Area Start -->
        <div class="foo_top_header_one section_padding_100_70">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="kilimanjaro_part">
                            <img src="/static/images/logo.jpg" style="max-width: 200px;" alt="">
                        </div>
                    </div>
                    
                    <div class="col-12  col-lg-3 kili-flex">
                        <div class="kilimanjaro_part">
                            <h5>KONTAKT</h5>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Telefon:</h5>
                                <p>+43 {{number.number}}</p>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Email:</h5>
                                <p style="font-size: 1rem;">office@fensterpro.at</p>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>Whatsapp:</h5>
                                <a aria-label="Chat on WhatsApp" href="https://wa.me/43{{number.number}}"> <img alt="Chat on WhatsApp" src="/static/images/WhatsAppButtonWhiteSmall.svg" />
                                </a>
                            </div>
                        </div>

                        <div class="kilimanjaro_part">
                            <h5>ÖFFNUNGSZEITEN</h5>
                            {% for day in openingHours%}
                            <div class="kilimanjaro_single_contact_info">
                                <h5>{{day.Days}}</h5>
                                {% for hour in day.hours_set.all%}
                                <p>{{hour.Hours}}</p>
                                {% endfor %}
                            </div>
                            {% endfor %}
                        </div>

                        <div class="kilimanjaro_part">
                            <h5>WICHTIGE LINKS</h5>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>
                                    <a href="{% url 'datenschutzerklärung' %}">Datenschutzerklärung</a>
                                </h5>
                            </div>
                            <div class="kilimanjaro_single_contact_info">
                                <h5>
                                    <a href="{% url 'impressum' %}">Impressum</a>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
              


    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script src="/static/js/scripts.js"></script>
</body>
</html>